### PR TITLE
add #[must_use] to see where we forget to use the call

### PR DESCRIPTION
**Pull request by mubarak23**

### CODE REVIEW

**Comment by antoyo** [comment]
@mubarak23: Sorry if I wasn't clear in the description. The PR needs to be done against the [gccjit.rs repository](https://github.com/rust-lang/gccjit.rs) and you need to add the `#[must_use]` attribute directly on the definition of the [function `Context::new_call()` right here](https://github.com/rust-lang/gccjit.rs/blob/9f8f67edc006d543b17529a001803ffece48349e/src/context.rs#L693) so that we get a warning on the usage of this function.
I hope this is more clear.

**Comment by mubarak23** [comment]
i see, i get this now, i will clone the repo and continue from their, it' best we close this PR, @antoyo

**Comment by mubarak23** [comment]
@antoyo checkout the [PR LINK](https://github.com/rust-lang/gccjit.rs/pull/30)

**Comment by antoyo** [comment]
Thanks. I'll check it out.

**Pull request closed without merging**
