### PR TITLE
rootsys flag for sysroot build

### PR DESCRIPTION
**Pull request by mubarak23**

### CODE REVIEW

**Comment by mubarak23** [comment]
this same bug is showing up here `error[E0463]: can't find crate for std` 

am yet to add the `--sysroot` in the CI

**Comment by antoyo** [comment]
I do not see any changes to add `--sysroot` to any of the [CI files](https://github.com/antoyo/rustc_codegen_gcc/tree/master/.github/workflows).

Plus, the sysroot is not even built even when providing this flag, so please debug in order to understand why your changes skip the build of the sysroot.

**Comment by mubarak23** [comment]
i did not add it  yet

**Comment by mubarak23** [comment]
am adding it to build command right i.e `./y.sh build --sysroot`

**Comment by mubarak23** [comment]
i found ` ./y.sh build --no-default-features --sysroot-panic-abort` inside gcc12.yml file, not sure if i need to add the sysroot flag here

**Comment by antoyo** [comment]
> i found ` ./y.sh build --no-default-features --sysroot-panic-abort` inside gcc12.yml file, not sure if i need to add the sysroot flag here

Yes, you need to add it.

Btw, it seems the sysroot is still not built. I suggest you add `println!` in a few places so that you understand why this happens.

**Comment by mubarak23** [comment]
alright,

**Comment by mubarak23** [comment]
add the println around `args.rootsys  `check and "--sysroot" =>

**Comment by mubarak23** [comment]
the prinntln i added build.rs are showing [here](https://github.com/antoyo/rustc_codegen_gcc/actions/runs/8455793704/job/23164108300?pr=13)

Build sysroot: false
Build sysroot: true

from here  ```
"--sysroot" => {
                    println!("Build sysroot: {}", build_arg.rootsys);
                    build_arg.rootsys = true;
                    println!("Build sysroot: {}", build_arg.rootsys);
                    return Ok(None);
                }

```

**Comment by mubarak23** [comment]
we have 5 success and 29 failed

**Comment by mubarak23** [comment]
is this good to go @antoyo

**Comment by antoyo** [comment]
The CI still have failures.
All the tests need to pass.
Please revert the formatting changes in the PR to make it easier to review.

Also, try to add `println!()` around all lines [in this function](https://github.com/antoyo/rustc_codegen_gcc/pull/13/files#diff-537a430b41250b3e1ff4f3e3478264a464352084986de735ff6142b4bc1b0438L215-L219).
Maybe this will help understand why the sysroot is not built.

**Comment by antoyo** [comment]
@mubarak23: What's the status of this?

**Comment by mubarak23** [comment]
am still struggling to find a solution to why the CI BUILD Fail

**Comment by mubarak23** [comment]
@antoyo we should close this PR, let me pick another issue to work

**Pull request closed without merging**
